--[[
	
	Made by: Sr_IP
	Date: 06/07/2023
	Modified : 17/07/2023

	]] --
local groupIDs = {}

groupIDs.EM = {
    MAIN = {
        ID = 13540523,
        TEAM = "Forest green" -- EJERCITO [1]
    },
    ALTOMANDO = {
        ID = 13540523,
        TEAM = "Medium blue" -- EJERCITO [1]
    }

}

groupIDs.MARINA = {
    MAIN = {
        ID = 13540601,
        TEAM = "Bright bluis green" -- 1 Marina 1
    },
    FAN = {
        ID = 33481034
    },
    PN = {
        ID = 33481029
    },
    UNOPES = {
        ID = 33481038
    },
    FES = {
        ID = 33481037
    }
}

groupIDs.FAM = {
    MAIN = {
        ID = 33481012,
        TEAM = "Bright orange" -- 1 FAM 4
    },

    BFP = {
        ID = 33481015,
        TEAM = "Cocoa" -- 1 FAM 4
    }
}

groupIDs.GN = {
    MAIN = {
        ID = 9129741, -- ORIGINAL: 4863102
        TEAM = "Institutional white" -- 1 GN 2 (PFP MAIN)
    },
    GENDARMERIA = {
        ID = 33481044
    },
    TRANSITO = {
        ID = 33481051
    }
}

groupIDs.PM = {
    MAIN = {
        ID = 33481016,
        TEAM = "Parsley green" -- 1 PM 2
    }
}

groupIDs.HCM = {
    MAIN = {
        ID = 33483010,
        TEAM = "Salmon" -- 1 PM 2
    }
}

groupIDs.AIC = {
    MAIN = {
        ID = 32758507,
        TEAM = "Oyster" -- 1 AIC
    },
    GL = {
        ID = 14337201,
        TEAM = "Medium blue"
    }

}

return groupIDs
