-- RaidSettingsModule.luau
-- ModuleScript for RaidSettings configuration

local RaidSettings = {
    Official = false,
    Mode = 1, -- 1: Easy, 2: Normal, 3: Hard
    CaptureTime = 1200,
    TermAmount = 0,
    Status = "UNOFFICIAL",
    AmbientMode = 1, -- 1: Night, 2: Day
    GameEnd = false,
    Counter = 0,
    Rollback = 0,
    TimesUp = false,
    -- Add other settings as needed
}

return RaidSettings
